### ISSUE TITLE
Shouldn't gendb.py and conifg.yaml be in the main directory?

### ISSUE THREAD

**Issue by arturbecker** [zhezh/TotalCapture-Toolbox#1]
I say this because when I tried to run gendb.py from gendata/gendb.py, it couldn't load the tools modules. So I moved gendb.py and config one directory up in the tree and it worked.

**Comment by zhezh** [comment]
This bug happens when not using pycharm to run gendb. 
Pycharm helps automatically import the project root directory into path.

30ec7abf534a8dc749c88d60cff56d0f9161abff should fix this bug.

**Comment by zhezh** [comment]
`export PYTHONPATH=".:$PYTHONPATH"; python gendata/gendb.py` to simulate Pycharm behavior would also work

**Comment by arturbecker** [comment]
Thanks, now it works perfectly from the home directory :)
