### ISSUE TITLE
about dataset where to download

### ISSUE THREAD

**Issue by PerhapsThat** [zhezh/TotalCapture-Toolbox#2]
│   │   ├── acting1_Xsens_AuxFields.sensors
│   │   ├── gt_skel_gbl_ori.txt
│   │   ├── gt_skel_gbl_pos.txt
│   │   ├── s1_acting1_calib_imu_bone.txt
│   │   ├── s1_acting1_calib_imu_ref.txt
│   │   ├── s1_acting1_Xsens.sensors

where can i find these files, I know acting1_BlenderZXY_YmZ.bvh file is in Vicon Groundtruth section, but where are the rest files, and gt_skel_gbl_pos.txt I really cannot find it.

**Comment by Garygi** [comment]
Just got tormented looking for it, and luckily I found it, so for the record:
│ │ ├── gt_skel_gbl_ori.txt
│ │ ├── gt_skel_gbl_pos.txt
These two files are in s1_vicon_pos_ori.tar.gz.
![图片](https://github.com/zhezh/TotalCapture-Toolbox/assets/81017111/3625ae98-20c1-41ea-93d6-506aa4ba638e)
And s1_vicon_pos_ori.tar.gz. Click Download in the area shown below. 
(Your format is txt format, but you say formatting is csv format, who are you? (っ ° Д °) っ)
![图片](https://github.com/zhezh/TotalCapture-Toolbox/assets/81017111/e53877a2-7754-4d3b-851c-8525d5ac73a5)

I hope the right people see it
